# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-12 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_answers_answerscollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerscollection',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_collection_set', to='repo.Answers', verbose_name='答题记录'),
        ),
    ]
